blank_issues_enabled: true
contact_links:
  - name: Content or feature request
    url: https://github.com/mdn/mdn/issues/new/choose
    about: Propose new content for MDN Web Docs or submit a feature request using this link.
  - name: MDN GitHub Discussions
    url: https://github.com/orgs/mdn/discussions
    about: Does the issue involve a lot of changes, or is it hard to split it into actionable tasks? Start a discussion before opening an issue.
  - name: MDN Web Docs on Discourse
    url: https://discourse.mozilla.org/c/mdn/learn/250
    about: Need help with assessments on MDN Web Docs? We have a support community for this purpose on Discourse.
  - name: Help with code
    url: https://stackoverflow.com/
    about: If you are stuck and need help with code, StackOverflow is a great resource.
