# This workflow is hosted at: https://github.com/mdn/workflows/blob/main/.github/workflows/idle.yml
# Docs for this workflow: https://github.com/mdn/workflows/blob/main/README.md#idle
name: "Label idle issues"

on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  mark-as-idle:
    uses: mdn/workflows/.github/workflows/idle.yml@main
    with:
      target-repo: "mdn/webextensions-examples"
